
#ifndef DNS_CONST_MPI_H_INCLUDED
#define DNS_CONST_MPI_H_INCLUDED

! MPI structures id
#define DNS_MPI_K_PARTIAL   1
#define DNS_MPI_K_SHEAR     2
#define DNS_MPI_K_POISSON   3
#define DNS_MPI_K_INFLOW    4
#define DNS_MPI_K_OUTBCS    5
#define DNS_MPI_K_TOPBCS    6
#define DNS_MPI_K_NRBCX     7
#define DNS_MPI_K_NRBCY     8
#define DNS_MPI_K_AUX1      9
#define DNS_MPI_K_AUX2     10

#define DNS_MPI_K_MAXTYPES 10

#define DNS_MPI_I_PARTIAL   1
#define DNS_MPI_I_SHEAR     2
#define DNS_MPI_I_POISSON1  3
#define DNS_MPI_I_POISSON2  4
#define DNS_MPI_I_AUX1      5
#define DNS_MPI_I_AUX2      6

#define DNS_MPI_I_MAXTYPES  6

#define MPIO_SUBARRAY_VISUALS_XOY  1
#define MPIO_SUBARRAY_VISUALS_ZOY  2
#define MPIO_SUBARRAY_VISUALS_XOZ  3
#define MPIO_SUBARRAY_PLANES_XOY   4
#define MPIO_SUBARRAY_PLANES_ZOY   5
#define MPIO_SUBARRAY_PLANES_XOZ   6
#define MPIO_SUBARRAY_BUFFER_JMIN  7
#define MPIO_SUBARRAY_BUFFER_JMAX  8
#define MPIO_SUBARRAY_SPECTRA_X    9
#define MPIO_SUBARRAY_SPECTRA_Z   10
#define MPIO_SUBARRAY_SPECTRA_XZ  11
#define MPIO_SUBARRAY_ENVELOPES   12

#define MPIO_SUBARRAY_SIZE        12

#endif
