
#ifndef LES_ERROR_H_INCLUDED
#define LES_ERROR_H_INCLUDED

#define LES_ERROR_TYPE         1000
#define LES_ERROR_ARM_SPECTRUM 1001
#define LES_ERROR_ARM_INI      1002
#define LES_ERROR_AVGPTS       1003
#define LES_ERROR_AVGTMP       1004
#define LES_ERROR_EVEN         1005
#define LES_ERROR_SIZEMPI      1006
#define LES_ERROR_FDFDIM       1007

#endif
