
#ifndef DNS_CONST_MPI_H_INCLUDED
#define DNS_CONST_MPI_H_INCLUDED

! MPI structures id
#define TLAB_MPI_TRP_K_PARTIAL   1
#define TLAB_MPI_TRP_K_SHEAR     2
#define TLAB_MPI_TRP_K_POISSON   3
#define TLAB_MPI_TRP_K_INFLOW    4
#define TLAB_MPI_TRP_K_OUTBCS    5
#define TLAB_MPI_TRP_K_TOPBCS    6
#define TLAB_MPI_TRP_K_NRBCX     7
#define TLAB_MPI_TRP_K_NRBCY     8
#define TLAB_MPI_TRP_K_AUX1      9
#define TLAB_MPI_TRP_K_AUX2     10

#define TLAB_MPI_TRP_K_MAXTYPES 10

#define TLAB_MPI_TRP_I_PARTIAL   1
#define TLAB_MPI_TRP_I_SHEAR     2
#define TLAB_MPI_TRP_I_POISSON1  3
#define TLAB_MPI_TRP_I_POISSON2  4
#define TLAB_MPI_TRP_I_AUX1      5
#define TLAB_MPI_TRP_I_AUX2      6

#define TLAB_MPI_TRP_I_MAXTYPES  6

#endif
